/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense, useEffect, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { useBox } from "@react-three/cannon";
import * as THREE from "three";
import { TextureLoader } from "three/src/loaders/TextureLoader.js";
import { Canvas, useFrame, useLoader } from "@react-three/fiber";
import { useState } from "react/cjs/react.development";
import { Color, MeshStandardMaterial } from "three";

export default function BathroomObj(props) {
  // const [mat, setMat] = useState(props.material)
  const [defaultTex, setDefaultTex] = useState(true);
  const [color, setColor] = useState("white");
  const [tex, setTex] = useState("blank.jpg");
  const [normalMap, setNormalMap] = useState("blank.jpg")
  const [shiftDown, setShiftDown] = useState(false)
  const normalTex = useTexture("/Textures/normalMaps/" + normalMap);
  const texture = useTexture("/Textures/" + tex);
  document.addEventListener("keydown", (e) => {
    if(e.key == "Shift" && !shiftDown){
      setShiftDown(true)
    }
  })
  document.addEventListener("keyup", (e) => {
    if(e.key == "Shift" && shiftDown){
      setShiftDown(false)
    }
  })
  texture.wrapS = THREE.RepeatWrapping;
  texture.wrapT = THREE.RepeatWrapping;
  return (
    <Suspense fallback={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={props.geometry}
        material={
          defaultTex
            ? props.material
            : new MeshStandardMaterial({
                color: color,
                map: texture,
                normalMap: normalMap === "blank.jpg" ? null : normalTex
              })
        }
        onClick={() => {
          if (props.clickable) {
            if(shiftDown){
              setDefaultTex(true)
            } else {
              setDefaultTex(false);
            }
            
            setColor(props.color);
            setTex(props.texture);
            switch (props.texture) {
              case "blank.jpg":
                setNormalMap("blank.jpg");
                break;
              case "wood_texture_01.jpg":
                setNormalMap("01.png");
                break;
              case "wood_texture_02.jpg":
                setNormalMap("02.png");
                break;
              case "wood_texture_03.jpg":
                setNormalMap("03.png");
                break;
              case "wood_texture_04.jpg":
                setNormalMap("04.png");
                break;
              case "wood_texture_05.jpg":
                setNormalMap("05.png");
                break;
            }
          }
        }}
      />
    </Suspense>
  );
}
